# Generated by Django 5.0.1 on 2024-01-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="user", max_length=150, unique=True
            ),
        ),
    ]
