# Generated by Django 5.0.1 on 2024-01-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="user",
                max_length=30,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
